# Generated by Django 4.0 on 2023-03-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='count_join',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authuser',
            name='count_report',
            field=models.IntegerField(default=0),
        ),
    ]
